name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Cache SBT dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
        restore-keys: |
          ${{ runner.os }}-sbt-

    - name: Set up Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: '11'
        scala-version: '2.13.6'
        distribution: 'adopt'

    - name: Build Scala project
      run: sbt compile

    - name: Test Scala project
      run: sbt test

    - name: Build Java with Gradle
      run: ./gradlew build

    - name: Publish to GitHub Pages
      if: github.ref == 'refs/heads/main'
      run: sbt ghpagesPushSite